# Generated by Django 5.0.6 on 2026-06-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
