# Generated by Django 5.0.6 on 2026-06-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_invoice_payment_terms"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesorderline",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
