# Generated by Django 5.0.6 on 2026-06-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_alter_salesorderline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="terms_conditions",
            field=models.TextField(blank=True),
        ),
    ]
