# Generated by Django 5.0.6 on 2026-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_salesorder_terms_conditions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoiceline",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
