# Generated by Django 5.0.6 on 2026-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_salesorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Invoice"),
                    ("credit_note", "Credit Note"),
                    ("debit_note", "Debit Note"),
                ],
                db_index=True,
                default="standard",
                max_length=20,
            ),
        ),
    ]
