# Generated by Django 5.0.6 on 2026-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_creditnote_creditnoteline_discountrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation'),
        ),
    ]
