# Generated by Django 5.0.6 on 2026-06-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesorder_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reject_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
    ]
