# Generated by Django 5.2.16 on 2026-09-02 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_alter_bankstatement_number_and_more'),
        ('company', '0007_intercompanysettlement_intercompanytransaction'),
        ('crm', '0008_alter_lead_number'),
        ('inventory', '0009_alter_cyclecount_number_alter_deliveryorder_number_and_more'),
        ('sales', '0014_alter_creditnote_number_alter_invoice_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_date'], name='sales_invoi_company_1141c9_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['sales_order', 'status'], name='sales_invoi_sales_o_212fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'sort_order'], name='sales_invoi_invoice_9e2fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='sales_payme_company_d67fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['invoice', 'status'], name='sales_payme_invoice_4b0cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', 'payment_date'], name='sales_payme_custome_10c447_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['company', 'status'], name='sales_quota_company_48478d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['company', 'status', 'order_date'], name='sales_order_company_6ca46b_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_sales_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('total__gte', 0), ('amount_paid__gte', 0), ('balance_due__gte', 0)), name='chk_invoice_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gte', models.F('invoice_date'))), name='chk_invoice_due_after_invoice_date'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='chk_invoice_line_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_sales_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payment_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_sales_quotation_number'),
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_amount__gte', 0), ('discount_amount__gte', 0), ('total__gte', 0)), name='chk_quotation_amounts_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='quotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='chk_quotation_line_valid'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='uniq_sales_order_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('tax_amount__gte', 0), ('discount_amount__gte', 0), ('total__gte', 0)), name='chk_so_amounts_non_neg'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_price__gte', 0), ('qty_delivered__gte', 0), ('qty_invoiced__gte', 0), ('qty_delivered__lte', models.F('quantity')), ('qty_invoiced__lte', models.F('quantity'))), name='chk_soline_quantities_valid'),
        ),
    ]
