# Generated by Django 5.2.16 on 2026-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectrisk_sprint_task_sprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
