# Generated by Django 5.0.6 on 2026-06-18 12:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Asset"),
                            ("liability", "Liability"),
                            ("equity", "Equity"),
                            ("revenue", "Revenue"),
                            ("expense", "Expense"),
                            ("cogs", "Cost of Goods Sold"),
                            ("bank", "Bank & Cash"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "account_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("current_asset", "Current Asset"),
                            ("fixed_asset", "Fixed Asset"),
                            ("current_liability", "Current Liability"),
                            ("long_term_liability", "Long-Term Liability"),
                            ("accounts_receivable", "Accounts Receivable"),
                            ("accounts_payable", "Accounts Payable"),
                            ("retained_earnings", "Retained Earnings"),
                            ("capital", "Capital"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_reconcilable", models.BooleanField(default=False)),
                ("allow_journal_entries", models.BooleanField(default=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("opening_balance_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_accounts",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_code", models.CharField(blank=True, max_length=50)),
                ("routing_number", models.CharField(blank=True, max_length=50)),
                ("swift_code", models.CharField(blank=True, max_length=20)),
                ("iban", models.CharField(blank=True, max_length=50)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_bank_accounts",
            },
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("description", models.CharField(max_length=500)),
                ("reference", models.CharField(blank=True, max_length=200)),
                ("is_reconciled", models.BooleanField(db_index=True, default=False)),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("source", models.CharField(default="manual", max_length=50)),
            ],
            options={
                "db_table": "accounting_bank_transactions",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=10)),
                (
                    "journal_type",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchase", "Purchase"),
                            ("cash", "Cash"),
                            ("bank", "Bank"),
                            ("general", "General"),
                            ("payroll", "Payroll"),
                        ],
                        max_length=15,
                    ),
                ),
                ("sequence_prefix", models.CharField(default="JE", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "accounting_journals",
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("reference", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("posted", "Posted"),
                            ("reversed", "Reversed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("is_reversal", models.BooleanField(default=False)),
                ("source_type", models.CharField(blank=True, max_length=50)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "accounting_journal_entries",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JournalItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "amount_currency",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("partner_type", models.CharField(blank=True, max_length=20)),
                ("partner_id", models.CharField(blank=True, max_length=100)),
                ("reconciled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "accounting_journal_items",
            },
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("tax_type", models.CharField(max_length=50)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_purchases",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "output_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "input_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "net_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submission_reference", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "db_table": "accounting_tax_returns",
            },
        ),
    ]
