# Generated by Django 5.2.16 on 2026-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auditlog_fixedasset_depreciationschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
