# Generated by Django 5.2.16 on 2026-10-09 10:04

from django.db import migrations, models

import apps.documents.validators


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[apps.documents.validators.validate_document_file]),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/versions/%Y/%m/', validators=[apps.documents.validators.validate_document_file]),
        ),
    ]
