# Generated by Django 5.0.6 on 2026-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventorytransfer_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorderline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryorderline',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventorytransferline',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
