# Generated by Django 5.2.16 on 2026-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_cyclecount_number_alter_deliveryorder_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('picking', 'Picking'), ('packing', 'Packing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20),
        ),
    ]
