# Generated by Django 5.0.6 on 2026-06-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_for_companies', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_for_companies', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_for_companies', to='accounting.account'),
        ),
    ]
