# Generated by Django 5.2.16 on 2026-08-26 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_accounting_lock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent company for hierarchical structures and financial consolidation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='company.company'),
        ),
    ]
