# Generated by Django 5.2.16 on 2026-08-26 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountingConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_country', models.CharField(default='US', max_length=2)),
                ('accounting_policy', models.CharField(choices=[('accrual', 'Accrual'), ('cash', 'Cash')], default='accrual', max_length=20)),
                ('lock_date', models.DateField(blank=True, null=True)),
                ('intercompany_posting_enabled', models.BooleanField(default=False)),
                ('is_consolidation_enabled', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_config', to='company.company')),
            ],
            options={
                'verbose_name': 'Accounting Configuration',
                'verbose_name_plural': 'Accounting Configurations',
                'db_table': 'company_accounting_configs',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('headquarters', 'Headquarters'), ('subsidiary', 'Subsidiary'), ('branch', 'Branch'), ('partner', 'Partner')], db_index=True, default='subsidiary', max_length=30)),
                ('country', models.CharField(default='US', max_length=2)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity', to='company.company')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entities',
                'db_table': 'company_legal_entities',
            },
        ),
        migrations.CreateModel(
            name='IntercompanyRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_method', models.CharField(choices=[('netting', 'Netting'), ('transfer', 'Transfer'), ('manual', 'Manual')], default='netting', max_length=20)),
                ('auto_posting_enabled', models.BooleanField(default=True)),
                ('allow_cross_currency', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_intercompany_rules', to='company.company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_intercompany_rules', to='company.company')),
            ],
            options={
                'verbose_name': 'Intercompany Rule',
                'verbose_name_plural': 'Intercompany Rules',
                'db_table': 'company_intercompany_rules',
                'unique_together': {('source_company', 'target_company', 'settlement_method')},
            },
        ),
    ]
