# Generated by Django 5.2.16 on 2026-09-01 04:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companyaccountingconfig_legalentity_intercompanyrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercompanySettlement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_intercompany_settlements', to='company.company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_intercompany_settlements', to='company.company')),
            ],
            options={
                'db_table': 'company_intercompany_settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntercompanyTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercompany_transactions', to='company.currency')),
                ('source_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_intercompany_transactions', to='company.company')),
                ('target_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_intercompany_transactions', to='company.company')),
            ],
            options={
                'db_table': 'company_intercompany_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_company', 'target_company', 'status'], name='company_int_source__dc09ae_idx')],
            },
        ),
    ]
