# Generated by Django 5.2.16 on 2026-10-09 10:01

from django.db import migrations, models
from django.utils.text import slugify


def populate_company_slugs(apps, schema_editor):
    Company = apps.get_model("company", "Company")
    database = schema_editor.connection.alias
    used_slugs = set()

    for company in Company._base_manager.using(database).order_by("pk").iterator():
        base_slug = slugify(company.name)[:100] or f"company-{company.pk}"
        candidate = base_slug
        suffix = 2
        while candidate in used_slugs:
            ending = f"-{suffix}"
            candidate = f"{base_slug[:100 - len(ending)]}{ending}"
            suffix += 1
        Company._base_manager.using(database).filter(pk=company.pk).update(
            slug=candidate
        )
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_sequencecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_company_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
