# Generated by Django 5.2.16 on 2026-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_maintenancerequest_materialplan_materialplanitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturingorder',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='materialplan',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='qualitycheck',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scraporder',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
