# Generated by Django 5.0.6 on 2026-06-28 12:23

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_workflowstep_branch_workflowstep_department_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflowdefinition",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="workflowinstance",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="approvaldelegation",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, only delegates for this specific workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workflow.workflowdefinition",
            ),
        ),
        migrations.AddField(
            model_name="workflowaction",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="workflow/attachments/"
            ),
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="canvas_layout",
            field=models.JSONField(
                default=dict, help_text="Stores node positions for visual designer"
            ),
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="notify_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="notify_in_app",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workflowdefinition",
            name="notify_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowinstance",
            name="current_step_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current step was assigned — used for escalation timing",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="approver_field",
            field=models.CharField(
                blank=True,
                help_text="Field on the document to use as approver, e.g. 'manager'",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="canvas_x",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="canvas_y",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="condition_rules",
            field=models.JSONField(
                default=list,
                help_text='[{"field":"amount","operator":"gte","value":10000,"next_step_order":3}]',
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="escalation_action",
            field=models.CharField(
                choices=[
                    ("notify", "Notify Again"),
                    ("reassign", "Reassign to Backup Approver"),
                    ("auto_approve", "Auto-Approve"),
                    ("auto_reject", "Auto-Reject"),
                ],
                default="notify",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="escalation_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="escalation_hours",
            field=models.PositiveIntegerField(
                default=24, help_text="Trigger escalation after N hours of inactivity"
            ),
        ),
        migrations.AddField(
            model_name="workflowstep",
            name="escalation_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Reassign to this user on escalation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_escalation_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("delegated", "Delegated"),
                    ("escalated", "Escalated"),
                    ("returned", "Returned for Clarification"),
                    ("noted", "Noted (FYI)"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="workflow_actions_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowaction",
            name="delegated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_delegated_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="conditions",
            field=models.JSONField(
                default=dict, help_text='{"amount__gte": 5000, "department_id": 3}'
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="trigger_event",
            field=models.CharField(
                choices=[
                    ("on_submit", "On Submit"),
                    ("on_create", "On Create"),
                    ("on_amount", "Amount Threshold"),
                    ("on_status_change", "On Status Change"),
                    ("manual", "Manual Trigger"),
                ],
                default="on_submit",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workflowdefinition",
            name="trigger_model",
            field=models.CharField(
                db_index=True,
                help_text="Model class name, e.g. 'LeaveRequest'",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="current_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_instances",
                to="workflow.workflowstep",
            ),
        ),
        migrations.AlterField(
            model_name="workflowinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("escalated", "Escalated"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="approver_role",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="approver_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "Specific User"),
                    ("role", "By Role"),
                    ("manager", "Direct Manager"),
                    ("department_head", "Department Head"),
                    ("dynamic", "Dynamic (from record field)"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="approver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workflow_approver_steps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="min_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("approval", "Approval"),
                    ("notification", "Send Notification"),
                    ("condition", "Condition (Branch)"),
                    ("action", "Auto Action"),
                ],
                default="approval",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WorkflowEscalationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("escalated_at", models.DateTimeField(auto_now_add=True)),
                ("action_taken", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True)),
                (
                    "escalated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalation_logs",
                        to="workflow.workflowinstance",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="workflow.workflowstep",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_escalation_logs",
                "ordering": ["-escalated_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowNotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("whatsapp", "WhatsApp"),
                            ("sms", "SMS"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("step_assigned", "Step Assigned (Pending Approval)"),
                            ("approved", "Workflow Approved"),
                            ("rejected", "Workflow Rejected"),
                            ("escalated", "Escalation Triggered"),
                            ("delegated", "Step Delegated"),
                            ("reminder", "Reminder"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "body",
                    models.TextField(
                        help_text="Use {{ document }}, {{ approver }}, {{ submitter }}, {{ company }}, {{ approve_url }}, {{ reject_url }}"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="workflow.workflowstep",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="workflow.workflowdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_notification_templates",
            },
        ),
    ]
