# Generated by Django 5.0.6 on 2026-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="segment",
            field=models.CharField(
                blank=True,
                help_text="Customer Segment (e.g., Enterprise, SMB)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
