# Generated by Django 5.2.16 on 2026-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_salestarget_territory_leadassignmentrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
    ]
