# Generated by Django 5.2.16 on 2026-08-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_installedapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import')], db_index=True, default='create', max_length=20),
        ),
    ]
