# Generated by Django 5.2.16 on 2026-10-06

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_auditlog_action'),
        ('authentication', '0002_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin'), ('SERVICE', 'Service'), ('SYSTEM', 'System'), ('CELERY', 'Celery'), ('API', 'API'), ('AI', 'AI'), ('ANONYMOUS', 'Anonymous')], db_index=True, default='SYSTEM', max_length=20)),
                ('service_account', models.CharField(blank=True, max_length=200)),
                ('actor_identifier', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('category', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('AUTHORIZATION', 'Authorization'), ('SECURITY', 'Security'), ('BUSINESS_DATA', 'Business Data'), ('FINANCIAL', 'Financial'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('INVENTORY', 'Inventory'), ('ACCOUNTING', 'Accounting'), ('HRMS', 'HRMS'), ('MANUFACTURING', 'Manufacturing'), ('POS', 'POS'), ('CRM', 'CRM'), ('PROJECTS', 'Projects'), ('HELPDESK', 'Helpdesk'), ('DOCUMENTS', 'Documents'), ('WORKFLOW', 'Workflow'), ('EXCEPTION', 'Exception'), ('API', 'API'), ('CELERY', 'Celery'), ('AI', 'AI'), ('SYSTEM', 'System'), ('ADMINISTRATION', 'Administration'), ('DATA_EXPORT', 'Data Export'), ('DATA_IMPORT', 'Data Import')], db_index=True, default='SYSTEM', max_length=40)),
                ('module', models.CharField(blank=True, db_index=True, max_length=80)),
                ('event_type', models.CharField(blank=True, db_index=True, max_length=80)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('object_reference', models.CharField(blank=True, max_length=500)),
                ('object_repr', models.CharField(blank=True, max_length=500)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('changed_fields', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('http_method', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('DENIED', 'Denied'), ('PARTIAL', 'Partial')], db_index=True, default='SUCCESS', max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('risk_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('event_hash', models.CharField(blank=True, db_index=True, max_length=128)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='company.company')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='company.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='company.department')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='authentication.user')),
            ],
            options={
                'db_table': 'admin_audit_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['company', 'created_at'], name='admin_audit__compan_3a1c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_user', 'created_at'], name='admin_audit__actor_u_8de0ec_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['module', 'created_at'], name='admin_audit__module_5bd4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['category', 'created_at'], name='admin_audit__catego_83ae0d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['correlation_id', 'created_at'], name='admin_audit__correla_8db0ea_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id', 'created_at'], name='admin_audit__reques_8c14d2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['model_name', 'object_id'], name='admin_audit__model_n_06f211_idx'),
        ),
    ]
