# Generated by Django 5.0.6 on 2026-06-18 12:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('asset_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('sold', 'Sold'), ('lost', 'Lost/Stolen')], db_index=True, default='active', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('depreciation_method', models.CharField(default='straight_line', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('disposal_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'assets_assets',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years', 'Sum of Years'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=20)),
                ('useful_life_years', models.PositiveSmallIntegerField(default=5)),
                ('salvage_value_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'assets_categories',
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Preventive'), ('corrective', 'Corrective'), ('predictive', 'Predictive')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assets_maintenances',
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'db_table': 'assets_depreciation_entries',
            },
        ),
    ]
