# Generated by Django 5.2.16 on 2026-07-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconfiguration',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Your Google Gemini API key. Overrides the server .env value.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='Your OpenAI secret key (sk-…). Overrides the server .env value.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='twilio_account_sid',
            field=models.CharField(blank=True, default='', help_text='Twilio Account SID for WhatsApp/SMS alerts.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='twilio_auth_token',
            field=models.CharField(blank=True, default='', help_text='Twilio Auth Token.', max_length=255),
        ),
        migrations.AddField(
            model_name='aiconfiguration',
            name='twilio_phone_number',
            field=models.CharField(blank=True, default='', help_text="Twilio 'from' phone number (e.g. +14155238886).", max_length=30),
        ),
    ]
