# Generated by Django 5.2.16 on 2026-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_ai_config_api_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Your Google Gemini API key. Overrides the server .env value.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='Your OpenAI secret key (sk-…). Overrides the server .env value.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='twilio_auth_token',
            field=models.CharField(blank=True, default='', help_text='Twilio Auth Token.', max_length=500),
        ),
    ]
