# Generated by Django 5.0.6 on 2026-06-24 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "module_source",
                    models.CharField(
                        choices=[
                            ("sales", "Sales Orders"),
                            ("purchases", "Purchase Orders"),
                            ("inventory", "Inventory Transactions"),
                            ("accounting", "Journal Items"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                            ("table", "Data Table"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                (
                    "group_by_field",
                    models.CharField(
                        help_text="The field to group the data by (e.g., status, created_at__month)",
                        max_length=100,
                    ),
                ),
                (
                    "aggregate_field",
                    models.CharField(
                        help_text="The field to calculate (e.g., total_amount, id)",
                        max_length=100,
                    ),
                ),
                (
                    "aggregate_function",
                    models.CharField(
                        choices=[
                            ("sum", "Sum"),
                            ("count", "Count"),
                            ("avg", "Average"),
                        ],
                        default="sum",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
