# Generated by Django 5.0.6 on 2026-06-28 12:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customreport",
            name="aggregate_field",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="customreport",
            name="group_by_field",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("sales_orders", "Sales Orders"),
                            ("invoices", "Invoices"),
                            ("customers", "Customers"),
                            ("leads", "Leads (CRM)"),
                            ("purchase_orders", "Purchase Orders"),
                            ("purchase_invoices", "Purchase Invoices"),
                            ("vendors", "Vendors"),
                            ("inventory", "Inventory / Stock"),
                            ("products", "Products"),
                            ("employees", "Employees"),
                            ("payroll", "Payroll"),
                            ("attendance", "Attendance"),
                            ("leave_requests", "Leave Requests"),
                            ("journal_entries", "Journal Entries"),
                            ("accounts", "Chart of Accounts"),
                            ("manufacturing_orders", "Manufacturing Orders"),
                            ("projects", "Projects"),
                            ("tasks", "Tasks"),
                            ("timesheets", "Timesheets"),
                            ("helpdesk_tickets", "Helpdesk Tickets"),
                            ("assets", "Fixed Assets"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list, help_text="List of field names to include"
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        default=dict, help_text="Dict of filter key->value pairs"
                    ),
                ),
                (
                    "sort_by",
                    models.CharField(blank=True, default="-created_at", max_length=100),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("none", "No Chart (Table Only)"),
                            ("bar", "Bar Chart"),
                            ("line", "Line Chart"),
                            ("pie", "Pie Chart"),
                            ("doughnut", "Doughnut Chart"),
                            ("area", "Area Chart"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "chart_group_by",
                    models.CharField(
                        blank=True,
                        help_text="Field to group/label chart by",
                        max_length=100,
                    ),
                ),
                (
                    "chart_value_field",
                    models.CharField(
                        blank=True, help_text="Field for chart values", max_length=100
                    ),
                ),
                ("enable_pivot", models.BooleanField(default=False)),
                ("pivot_row", models.CharField(blank=True, max_length=100)),
                ("pivot_col", models.CharField(blank=True, max_length=100)),
                ("pivot_value", models.CharField(blank=True, max_length=100)),
                (
                    "company_id",
                    models.IntegerField(blank=True, db_index=True, null=True),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, help_text="Visible to all users in the company"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports_saved_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Every 2 Weeks"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("xlsx", "Excel (XLSX)"),
                            ("csv", "CSV"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                (
                    "recipients",
                    models.TextField(help_text="Comma-separated email addresses"),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="analytics.savedreport",
                    ),
                ),
            ],
            options={
                "db_table": "reports_scheduled_report",
            },
        ),
        migrations.CreateModel(
            name="ReportExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("export_format", models.CharField(blank=True, max_length=10)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="analytics.savedreport",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="analytics.scheduledreport",
                    ),
                ),
            ],
            options={
                "db_table": "reports_execution",
                "ordering": ["-started_at"],
            },
        ),
    ]
