# Generated by Django 5.0.6 on 2026-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_autopurchaserule_purchasecontract_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("sent", "Sent to Vendor"),
                    ("confirmed", "Confirmed"),
                    ("partial", "Partially Received"),
                    ("received", "Fully Received"),
                    ("invoiced", "Invoiced"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
