# Generated by Django 5.2.16 on 2026-09-10 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_bill_number_alter_goodsreceipt_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('matched', '3-Way Matched'), ('mismatch', 'Mismatch Flagged'), ('overridden', 'Mismatch Overridden')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='mismatch_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bill',
            name='mismatch_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_bills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bill',
            name='mismatch_override_reason',
            field=models.TextField(blank=True),
        ),
    ]
