# Generated by Django 5.0.6 on 2026-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('totp', 'Authenticator App')], default='totp', max_length=10),
        ),
    ]
