# Generated by Django 5.0.6 on 2026-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usercompany_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepermission',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
    ]
