# Generated by Django 5.2.16 on 2026-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_modulepermission_can_consolidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
